### ISSUE TITLE
Q&A: caching

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#11]
since the extension caches the video to avoid buffering, does the cache gets removed automatically once the webpage or browser is closed?

or does it perform differently?

**Comment by Andrews54757** [comment]
Yes. The cache gets removed automatically. On Chrome, the cache is stored as [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects, these will be deleted automatically by your browser when nothing is using it. However, on Firefox, the cache is stored in an [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) database because Firefox can't store Blobs in anything but RAM. As such, the Firefox version is the only version where it is technically possible for persistent data to be "orphaned" after you close the tab. To prevent this from happening, the Firefox version listens for the [`unload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event) event to clean up the database when the page is closed. Should that fail (when your browser/computer crashes), additional checks are done upon initialization of the player so that any leftover data is removed.

**Comment by bachig26** [comment]
> Yes. The cache gets removed automatically. On Chrome, the cache is stored as [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects, these will be deleted automatically by your browser when nothing is using it. However, on Firefox, the cache is stored in an [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) database because Firefox can't store Blobs in anything but RAM. As such, the Firefox version is the only version where it is technically possible for persistent data to be "orphaned" after you close the tab. To prevent this from happening, the Firefox version listens for the [`unload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event) event to clean up the database when the page is closed. Should that fail (when your browser/computer crashes), additional checks are done upon initialization of the player so that any leftover data is removed.

awesome, thank you so much 👍❤
