### ISSUE TITLE
[BUG] Buggy pause/play functionality

### ISSUE THREAD

**Issue by justlukie** [Andrews54757/FastStream#124]
When I have the extension enabled in YouTube, and use the pause/play controls on my Bluetooth headphones, both the original YouTube video player and the FastStream video player react and I start hearing two different audio streams.

**Comment by RNavarro3000** [comment]
I've seen similar issues but on other sites, so not site specific. I don't have bluetooth headphones, so not specific to that either. For me, it happens when I click on the video to start playback, it looks like the click triggers play back in FastStream and also the web site's native video player at the same time. It's sporadic to me, once every 25 videos or so, so I haven't thought about it too much. From the behavior I've seen, feels like FastStream doesn't disable the native player, but overlays on top of it and sometimes the click or "play" directive bleeds through to the native player....

**Comment by Andrews54757** [comment]
@RNavarro3000 That is accurate. It is a known bug that the player replacement sometimes fails, especially on Youtube. it is difficult to debug because I am unable to reproduce it on demand. I am working on it though.

**Comment by Andrews54757** [comment]
Fixed
