### ISSUE TITLE
exit menu options when clicking outside the scope

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#21]
**Is your feature request related to a problem? Please describe.**
current functionality: for example with the subtitle menu, the user needs to toggle the cc button to open and close the menu.

**Describe the solution you'd like**
expected functionality: exiting/closing the menu by clicking anywhere outside similar to other players like html5, for example how youtube default player functions.

**Comment by Andrews54757** [comment]
This was intended behavior back when the subtitle track resync tool (hourglass icon) didn't exist. You had to click the four little triangle buttons to nudge the subtitles, but because there was no visual feedback, it was difficult to discern proper timing. Hence, user would often have to re-adjust multiple times. Persistent showing of the captions menu was helpful in this case, as you didn't have to click the subtitle menu button over and over.

I'll consider changing this, but personally I think that there may still be some utility in having the menu stay on until the user closes it, especially since it is an accessibility feature.

**Comment by Andrews54757** [comment]
I think I've decided that I'm not going to implement this. You can already close all windows by clicking the video itself. Having the windows close upon interaction with the control bar will be more inconvenient towards people who like changing things frequently.
