### ISSUE TITLE
[Feature] New configuration options

### ISSUE THREAD

**Issue by Dioswilson** [Andrews54757/FastStream#24]
Hello, i'd like to suggest some configuration options I currently use on  youtube, either as a youtube feature or from  [Enhancer for YouTube™](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle).
- Allow pause with a single click on the player
- Have more reproducion speeds, with at least up to x5 speed
- Set a default reproduction speed other than x1
- Allow to change reproduction speed with control+scrolwheel and/or a keybind
- Allow to enter fullscreen by double clicking
- Option to enable autoplay when player launches

**Comment by Andrews54757** [comment]
Thanks for your suggestions! Here are some thoughts I had.

> Allow pause with a single click on the player

FastStream currently will play/pause the video upon double clicking. Single clicks are reserved for hiding the player controls. It is the same behavior for QuickTime player on MacOS. I like having an easy way to hide the controls more than playing/pausing, especially since there is also a keybind (space) for it.

> Have more playback speeds, with at least up to x5 speed

Sure! I can do this, I'll make it support up to 8x. https://github.com/Andrews54757/FastStream/commit/9d7d205b6be8aa3baab793c2056a5ea839010f7d

> Set a default reproduction speed other than x1

Sure! I can do this. https://github.com/Andrews54757/FastStream/commit/33e2140bf99ce5a98716efc209965d02808ddd46

> Allow to change reproduction speed with control+scrollwheel and/or a keybind

Sure! I can do this. `Shift+ArrowUp` and `Shift+ArrowDown` will be the new keybinds to adjust playbackrate by 0.1. https://github.com/Andrews54757/FastStream/commit/e8bbaebecfae52fb01f39a6f630324b00411742d

> Allow to enter fullscreen by double clicking

Double clicking is reserved for play/pause toggle. I suggest using the Fullscreen keybind `f` instead to quickly enter fullscreen mode.

> Option to enable autoplay when player launches

Autoplay will not be supported, see #7.


New features will be available in FastStream 1.2.5 (or now if you install from source).

**Comment by Dioswilson** [comment]
Could you maybe add an option to pause/unpause with just one click instead of hiding player's info? Maybe add a configurable mouse binding? 
Also regarding fullscreen, I usually am a mouse hater who uses vim, but for some reason when watching youtube I just use the mouse to navigte with no hands on the keyboard. As with the previous issue maybe this could be fixed by customizable click mappings configuration or smth similar

**Comment by Andrews54757** [comment]
> Could you maybe add an option to pause/unpause with just one click instead of hiding player's info? Maybe add a configurable mouse binding?

Maybe in the future, but I don't see a way to support having custom mouse bindings easily right now.

**Comment by Andrews54757** [comment]
1. `Single Click Toggles Play/Pause` option is now available in V1.2.5 to enable play/pause with single click instead of hiding the player
2. Autoplay was added back on just Youtube due to popular demand (can trust Youtube.com enough as a special exception) in V1.2.6 https://github.com/Andrews54757/FastStream/commit/cc3272bbcc8522136f41c1b4afde867316a11c30

**Comment by azhinu** [comment]
But there is still no double click to fullscreen option.

**Comment by Andrews54757** [comment]
@azhinu Double click fullscreen is not planned. Double click is currently used for play/pause and will require adding another configuration option to make it toggle fullscreen. I also don't personally like double click fullscreen because I often double click things by accident. I'll still consider it when I re-write the configurations code.

**Comment by Andrews54757** [comment]
@azhinu Double click fullscreen option (and more) is implemented in https://github.com/Andrews54757/FastStream/commit/350471f5808c54601dfb67761d840f033ac14a61

Will be available in V1.2.13
