### ISSUE TITLE
[BUG] On a streaming site, cannot save some downloads

### ISSUE THREAD

**Issue by Bolongna** [Andrews54757/FastStream#242]
Can fully buffer most videos in full hd, however if the video is longer than about 2 hrs it will not allow it to be saved. It will show the cont going up to 100% then an error screen shows up saying it cannot save the video and asks if I would like to save the buffer contents. for movies of "normal" length it seems to work fine. I increased the pre-download size to far over what the video should need but no change. 

This is the latest chrome version running on chrome that is up to date. running on W11

The site is ( https://fmovies.ps/ ) but I've had it happen on others as well. Primarily when trying to save the LOTR movies or others that are over 2.5 hrs or so in full HD.

**Comment by Andrews54757** [comment]
FastStream is not designed to download large media files and such will not be supported in the near future due to limits on resources. Please use a different tool such as VLC to process large files.

Nevertheless, you have brought to my attention that FastStream's saving code required some refactoring, I have since updated the code to properly handle 64 bit byte offsets.
