### ISSUE TITLE
[BUG] 4K Youtube Videos Not Playing in 4K via FastStream

### ISSUE THREAD

**Issue by 488GTB** [Andrews54757/FastStream#255]
For a couple of Weeks now, 4K Youtube videos will only play at 1080p in Firefox using FastStream.
(4K works if FastStream not used, but stutters a bit.)

The Options for 1440P and 2160p have gone missing.

Version 1.3.29

Platform**
Firefox 130.0.1 64-bit on Windows 10 64-bit. 

Watch any YouTube 4K video. Click the FastStream and it only plays at 1080p
Example: https://www.youtube.com/watch?v=bJ7ADjD8nAU&list=WL&index=3&t=1326s

**Comment by Andrews54757** [comment]
We had to change client to IOS mode after WEB stopped functioning, again, due to Google changing the way Youtube works. Youtube is phasing out dash streams on WEB in favor of a SABR based system. People are working on figuring out the new system, but until then we have to use the IOS client which means reduced quality choices for certain videos.

Youtube's changes roll out incrementally though, so you might be able to squeeze out a little bit more life out of the WEB client if you're lucky. Export your faststream settings to a JSON file, and with a text editor change `dev` from `false` to `true`. Load the file into faststream, and you should see more options for choosing the YT client to use. Change it from `IOS` to `WEB`. if you are lucky, youtube should still work after you do that. if not, then your IP is likely affected and you will have to use the `IOS` client.

**Comment by mayaamis** [comment]
@Andrews54757  I dont want to open new thread because I dont have a bug to report or anything I just can't find any other place to contact you so I will ask here. If we enable "Predownload videos" is there a specific location on disk where they are stored? If yes what is it? Also where do screenshots go? I took a few and literally could not manage to find where it go, checked all the usual places downloads, my documents- videos, pictures, even app data folder.. I cant figure it out. just curious :)

as for the player itself it works great the only issue so far I noticed is it wont load properly on some special youtube member videos. like the video that is only visible for members that I am a part of bbut not for general public yet. but I dont find this an issue and it's a rare occasion.

**Comment by Andrews54757** [comment]
Screenshots go in the downloads folder. as for predownloaded videos, they are stored temporarily and then automatically deleted by your browser when you close the tab. On chrome you can find where they are stored by going to `chrome://blob-internals`. Learn more about how Chrome handles blobs here: https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md

**Comment by mayaamis** [comment]
@Andrews54757  I'm not using chrome I'm using your plugin with firefox. as for screenshots they are deff not in Downloads I looked there many times :)

**Comment by Andrews54757** [comment]
It should be fixed now in 1.3.29.1, there was a bug with saves not working.

**Comment by Andrews54757** [comment]
We are making the WEB client default again, with IOS fallback. this should solve this issue for most users.

**Comment by mayaamis** [comment]
that's great news :)
