### ISSUE TITLE
[BUG] Video not detected on ok.ru

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#51]
**Describe the bug**
Video not detected

**Version**
FastStream V1.2.12

**Platform**
Firefox

**Steps to Reproduce**
Sample link: ok.ru/video/7803363133968
The video isn't detected so FastStream do not work at all on the sample link provided.

**Comment by Andrews54757** [comment]
It seems like their website doesn't use the standard naming convention for stream manifests. Instead of URLs ending with a `.m3u8` or `.mpd` they use a long query string:
```
https://vd343.mycdn.me/?expires=1702952511283&srcIp=[redacted]&pr=10&srcAg=CHROME_MAC&ms=[redacted]&type=1&sig=kThi2hIuDQE&ct=6&urls=[redacted]&clientType=0&zs=43&id=5978708576784
```

This is not detectable using FastStream as of this moment. It is not possible to detect this without having a hardcoded list of URL patterns. Since I don't plan on maintaining a fixed set of patterns, I will add a feature so that you can add custom patterns yourself.

Note: Having broad custom patterns may be computationally expensive.

**Comment by ale5000-git** [comment]
I don't know the internal details of FastStream but can't generically detect all video elements in the DOM?

**Comment by Andrews54757** [comment]
Detecting the video element isn't the issue. The problem is that you need to detect the source of the video. This is detected by monitoring network requests. The DOM doesn't reveal information about the video source when it is a stream.

**Comment by Andrews54757** [comment]
Custom source pattern support added https://github.com/Andrews54757/FastStream/commit/6500ee746c29f19838ad891a7a748b7f583a9174

Go to settings and paste this into the custom source patterns text box.
```
# Custom pattern for ok.ru/video/
mpd /^https:\/\/vd[0-9]*\.mycdn\.me\/\?.*&type=1&/
```

**Comment by ale5000-git** [comment]
It works perfectly, thanks.
