### ISSUE TITLE
[BUG] - Subtitle not showing when using PiP

### ISSUE THREAD

**Issue by akumaaayush** [Andrews54757/FastStream#54]
**Describe the bug**
The subtitle in the video isnt showing in the PiP window. Instead it's showing in the main video frame

**Version**
1.2.11

**Platform**
Chrome 

**Steps to Reproduce**
Hit PiP on a video with subtitles on. 

**Image:**
![image](https://github.com/Andrews54757/FastStream/assets/58813006/1ffc1a38-d029-4e1d-98c7-584ff3276f8f)

This was in fmoviesz dot to.
Thanks for the awesome extension :D

**Comment by akumaaayush** [comment]
Updated extension to 1.2.13 and it's there still.

**Comment by Andrews54757** [comment]
This is not something I can implement as of yet. Web browsers don't yet have a standardized API to enable captions when using PIP mode. See https://bugs.chromium.org/p/chromium/issues/detail?id=854935

I will look into implementing a basic version that uses the unnoficial [Document Picture-in-Picture API](https://wicg.github.io/document-picture-in-picture/)

**Comment by Andrews54757** [comment]
I've attempted to implement document PIP https://github.com/Andrews54757/FastStream/commit/118392ab1a94165643ed5d72a3f107ada817de55

Unfortunately, it fails to work because Chrome doesn't yet allow its usage on extension pages. It throws an error:
```
Uncaught (in promise) DOMException: Failed to execute 'requestWindow' on 'DocumentPictureInPicture': Opening a PiP window requires https or file protocol
```

Here is the related bug report:
https://github.com/WICG/document-picture-in-picture/issues/101
