### ISSUE TITLE
[Feature] Arc auto PiP support

### ISSUE THREAD

**Issue by exdeniz** [Andrews54757/FastStream#55]
In Arc 

Arc has an "Enable Picture in Picture when you leave a video tab" feature, it's very handy. But now FastStream behavior is such that when you switch tabs, pip not only does not appear, but switches from pip back to player.

**Comment by Andrews54757** [comment]
Added in https://github.com/Andrews54757/FastStream/commit/c7f4dc9d452692380019abb2afd0086b36bad041

Note that you have to interact with the player first to allow it to enter picture in picture.

**Comment by Andrews54757** [comment]
After more testing, it appears like PIP is only allowed within 5 seconds of a user gesture. Otherwise, it will not work. So I have removed this feature for now. Google/Firefox/etc will have to implement this on their end for it to work reliably. See
https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/issues/20
