### ISSUE TITLE
[BUG] Weird name for the subtitle track on drivejwplayer.xyz

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#58]
**Describe the bug**
Weird name for the subtitle track

**Version**
FastStream V1.2.15

**Platform**
Firefox

**Steps to Reproduce**
Sample link: drivejwplayer.xyz/embed/t5kwvgsw4rhqn-b?alt=7268
It has a weird name for the subtitle track; it would be nice if it can display the language of the subtitles.

PS: Since it actually has both hardsub and softsub it would also be nice if possible to have an option to move the softsub vertically to avoid displaying them over the hardsub.

**Comment by Andrews54757** [comment]
Subtitles track names are determined by the name of the track as given by the website. This is for accessibility reasons and it will not be changed. The language of the subtitles is autodetected and visible in the parenthesis. The `(id)` tag indicates that it is in Indonesian. Please see https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes

The ability to move subtitles will be added when I have time.

**Comment by ale5000-git** [comment]
Is it possible to enforce maximum title length to a sensible value?

**Comment by Andrews54757** [comment]
Done https://github.com/Andrews54757/FastStream/commit/6ec31dc1217318f80334130aec3b62faccf79b1d

**Comment by Andrews54757** [comment]
Vertically moveable subtitles added in https://github.com/Andrews54757/FastStream/commit/3bd337ace74e65ccfdcea4f73fb83dbfa9d4f9e1

**Comment by ale5000-git** [comment]
Thanks a lot :-)

**Comment by gemen7** [comment]
hello guys...i am sure this is the wrong thread but i cannot seem to find were to ask a question for you. I am using the great huawei p60pro mobile thanks to YOU all and your wonderful microg services etc. :) I got if you are kind enough 2 questions :
1)is it ever possible to sync contacts? (calendar syncs just fine:) )
2)the most important....some apps started (i guess because the google services need update or the core microg uses older google services version) crashing and telling that they cannot function because google services is outdated or not exist in my phone . How can this thing be fixed? waiting for a newer microg +gsmcore version? should i update google play services via aurora store or it will mess up everything? if a newer version fixes this of microg or gsm how can it be updated? Sorry if i messed up a lot of issues i hope you understand :) and once more THANKS A LOT. going to contribute as well :) Have a great new year all!
