### ISSUE TITLE
[Feature] Sponsorblock Integration

### ISSUE THREAD

**Issue by NotMithical** [Andrews54757/FastStream#66]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Configurable integration with Sponsorblock to highlight, skip, mute, or prompt to skip sponsored segments of the video

**Comment by Andrews54757** [comment]
Duplicate. See #16

**Comment by NotMithical** [comment]
I see. Is the basic support you mentioned in your last comment on that issue still functional? And if so, does it require any setup beyond having SB installed?

**Comment by Andrews54757** [comment]
Yes, it should be functioning. No other setup is required. Make sure the skip sections are visible in the progress bar.

**Comment by NotMithical** [comment]
The sections are visible before I turn on FS, but they disappear once its enabled and no sections are skipped.

**Comment by Andrews54757** [comment]
what browser are you using?

**Comment by NotMithical** [comment]
Firefox 121.0.1 on Windows

**Comment by NotMithical** [comment]
It started working recently, at least to an extent. Sponsored segments are highlighted when I hover over the timeline and I get prompted to skip segments, but they still aren't skipped automatically when faststream is enabled.

**Comment by Andrews54757** [comment]
@NotMithical I believe automatic skipping was never enabled on FastStream. You have to press a keybind, or click the skip button to skip segments.

Currently, there is no way for FastStream to know whether the autoskip setting is set in SponsorBlock. FastStream's code supports automatic skipping, but it is unused because FS doesn't have official integration with SponsorBlock.

**Comment by NotMithical** [comment]
Ah, ok. Is there any possibility of a separate toggle for autoskipping being added in faststream at some point?
