### ISSUE TITLE
auto add the URL when toggled

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#8]
with current system, the user need to add the URL say `https://youtube.com/` to the `Auto-enable URLs` for automatically enabling the extension without using the toggle.

but having an intermediate function that adds the URL directly to the `Auto-enable URLs` box when toggling the extension on it's 1st time on that particular URL. with further toggles can be made on that site to temporarily switch the default player would be nice.

**Comment by Andrews54757** [comment]
This wouldn't work because the player has no way of knowing what part of the URL to include. Take for example this structure:

> https://example.com/movie/moviename/1

Ideally you would want to turn on the extension whenever you see

> https://example.com/movie/

In the URL. But how do you know if you should include/exclude `moviename/1`? It's something that the user has to provide.
