### ISSUE TITLE
[Feature] Setting to allow video cache for __ time

### ISSUE THREAD

**Issue by blox11** [Andrews54757/FastStream#85]
**Is your feature request related to a problem? Please describe.**
Ability to cache video for user defined time period.

**Describe the solution you'd like**
Option in the settings menu to toggle video caching and the amount of time before it expires and/or a size limit is reached in megabytes.

**Describe alternatives you've considered**
A button in the video player window to manually cache specifically that video.

**Additional context**

**Comment by Andrews54757** [comment]
Persistent video storage is not planned due to storage constraints on the browser. The browser may run out of storage space. 

You can "cache" a video by saving it to a file. Hold down SHIFT and click the download button to dump the player's buffer. You can then drag and drop it over the player to resume later.
